apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: nfs-manual # Deve coincidere con il PV
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
