apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-pvc
spec:
  containers:
  - name: web-server
    image: nginx
    volumeMounts:
    - name: nfs-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc  # Si aggancia al PersistentVolumeClaim chiamato nfs-pvc
