Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.hostname = "nodo1"
    nodo1.vm.network "private_network", ip: "192.168.33.11"
    nodo1.vm.provision "shell", path: "scripts/setup_docker.sh"
  end

  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.hostname = "nodo2"
    nodo2.vm.network "private_network", ip: "192.168.33.12"
    nodo2.vm.provision "shell", path: "scripts/setup_docker.sh"
  end

   config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
end
