apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nginx-http-check
  namespace: monitoring  # Deve stare dove c'è Prometheus o essere visibile
  labels:
    release: monitoring  # Questa label serve a Prometheus per "notare" questo oggetto
spec:
  jobName: http-probe-nginx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115    # Indirizzo del pod Blackbox
  module: http_2xx       # Modulo standard: si aspetta status code 200-299
  targets:
    staticConfig:
      static:
      - http://nginx-service.default.svc.cluster.local:80 
  interval: 15s
