Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "nfs-server"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Questi comandi vengono eseguiti al primo avvio per installare NFS per avere un ambiente pronto già dall'avvio
  config.vm.provision "shell", inline: <<-SHELL
    echo "Installazione NFS Server"
    apt-get update
    apt-get install -y nfs-kernel-server

    echo "Configurazione Cartella"
    mkdir -p /srv/nfs/share
    chown nobody:nogroup /srv/nfs/share
    chmod 777 /srv/nfs/share

    echo "Configurazione Exports"
    # Esporto a tutti (*) con permessi rw e no_root_squash
    echo "/srv/nfs/share *(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports

    echo "Riavvio Servizio"
    exportfs -a
    systemctl restart nfs-kernel-server
    
    echo "VM PRONTA: NFS Server Attivo"
  SHELL
end
