apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-direct
spec:
  containers:
  - name: web-server
    image: nginx
    volumeMounts:
    - name: nfs-share
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nfs-share
    nfs:
      server: 10.107.98.215  # IP DEL MIO SERVICE NFS
      path: /      # quando il Pod chiede di montare /nfsshare, il server non sa di cosa parlo perché lui si aspetta che chiedo semplicemente /
